#!/usr/bin/env python

# -*- coding: utf-8 -*-
import re
import sys

sys.path.append('libs/TextAttack')
sys.path.append('libs/xu_auto_LiRPA')

import patched
from unittest.mock import patch

from textattack.commands.textattack_cli import main

@patch('textattack.loggers.AttackLogManager', new=patched.AttackLogManager)
def patched_main():
    main()

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(patched_main())
